[package]
name = "avtime"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rsntp = "4.1"
chrono = "0.4"
tokio = { version = "1.42", features = ["full"] }
